/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HeatmapPlot: typeof import('./components/HeatmapPlot.vue')['default']
    PlotControls: typeof import('./components/PlotControls.vue')['default']
    PlotVuer: typeof import('./components/PlotVuer.vue')['default']
    PlotVuerOriginal: typeof import('./components/PlotVuer-original.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeseriesPlot: typeof import('./components/TimeseriesPlot.vue')['default']
  }
}
